options:
  source:
    type: string
    default: "ppa:canonical-bootstack/thruk"
    description: "PPA to install thruk"
  nagios_context:
    type: string
    default: "bootstack"
    description: "Name for the thruk instance"
  livestatus_path:
    type: string
    default: "/var/lib/nagios3/livestatus/socket"
    description: "Path to livestatus socket"
  nagios_context:
    default: "juju"
    type: string
    description: >
      Used by the nrpe-external-master subordinate charm.

      A string that will be prepended to instance name to set the host name
      in nagios. So for instance the hostname would be something like:

        juju-myservice-0

      If you're running multiple environments with the same services in them
      this allows you to differentiate between them.

