#!/usr/bin/python3

import amulet
import requests

seconds = 180000

d = amulet.Deployment(series='trusty', juju_deployer='juju-deployer -d -v')

print("LOG: Adding charms")

d.add('nagios')
d.add('thruk-agent')

print("LOG: Relating charms")
d.relate('nagios:juju-info', 'thruk-agent:general-info')

print("LOG: Exposing charms")
d.expose('nagios')

print("LOG: Configuring charms")
d.configure('nagios', {'enable_livestatus': True})

print("LOG: Setting up environment")
try:
    d.setup(timeout=seconds, cleanup=False)
    d.sentry.wait()
except amulet.helpers.TimeoutError:
    amulet.raise_status(amulet.SKIP, msg="Environment wasn't stood up in time")
except:
    raise


##
# Set relationship aliases
##
nagios_unit = d.sentry.unit['nagios/0']
# Can't use a subordinate as a sentry unit
# thruk_agent_unit = d.sentry.unit['thruk-agent/0']

print("LOG: Getting passwords")
try:
    thrukpwd = nagios_unit.file_contents('/var/lib/thruk/thrukadmin.passwd').strip()
except:
    raise

print("LOG: Testing thruk url")
host_url = ("http://%s/thruk/")
try:
    r = requests.get(host_url % nagios_unit.info['public-address'],
                     auth=('thrukadmin', thrukpwd))
except:
    raise
