#!/usr/bin/python3

import amulet
import requests

seconds = 90000

d = amulet.Deployment(series='trusty')

d.add('nagios')
d.add('thruk-agent')

d.relate('nagios:juju-info', 'thruk-agent:general-info')

d.expose('nagios')

d.configure('nagios', {'enable_livestatus': True})

try:
    d.setup(timeout=seconds)
    d.sentry.wait()
except amulet.helpers.TimeoutError:
    amulet.raise_status(amulet.SKIP, msg="Environment wasn't stood up in time")
except:
    raise


##
# Set relationship aliases
##
nagios_unit = d.sentry.unit['nagios/0']
thruk_agent_unit = d.sentry.unit['thruk-agent/0']

thrukpwd = thruk_agent_unit.file_contents('/var/lib/thruk/thrukadmin.passwd').strip()

host_url = ("http://%s/thruk/")
try:
    r = requests.get(host_url % thruk_agent_unit.info['public-address'],
                     auth=('thrukadmin', thrukpwd))
except:
    amulet.raise_status(amulet.ERROR, msg="Can't get to thruk URL")
