#!/usr/bin/python3

import amulet
# import requests

seconds = 90000

d = amulet.Deployment(series='trusty')

d.add('nagios')
d.add('thruk-agent')

d.relate('nagios:juju-info', 'thruk-agent:general-info')

d.expose('nagios')

try:
    d.setup(timeout=seconds)
    d.sentry.wait()
except amulet.helpers.TimeoutError:
    amulet.raise_status(amulet.SKIP, msg="Environment wasn't stood up in time")
except:
    raise


##
# Set relationship aliases
##
nagios_unit = d.sentry.unit['nagios/0']
thruk_agent_unit = d.sentry.unit['thruk-agent/0']

